# Generated by Django 2.2.13 on 2020-10-30 10:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['versao', 'evento', 'operacao', 'status'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='identidade',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='nrinsc',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='procemi',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='tpamb',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='tpinsc',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='verproc',
        ),
        migrations.AddField(
            model_name='eventos',
            name='evento',
            field=models.CharField(blank=True, default='v02_05_00', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/PycharmProjects/emensageria/certificado/'), upload_to=''),
        ),
    ]
