# Generated by Django 2.2.13 on 2020-10-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0002_auto_20201030_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='identidade',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
