# Generated by Django 2.2.13 on 2020-10-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0003_eventos_identidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='evento_json',
            field=models.TextField(blank=True, null=True, verbose_name='evento_json'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ocorrencias_json',
            field=models.TextField(blank=True, null=True, verbose_name='ocorrencias_json'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='retorno_consulta_json',
            field=models.TextField(blank=True, null=True, verbose_name='retorno_consulta_json'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='retorno_envio_json',
            field=models.TextField(blank=True, null=True, verbose_name='retorno_envio_json'),
        ),
    ]
