# Generated by Django 2.2.13 on 2020-10-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0004_auto_20201030_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='evento',
            field=models.CharField(blank=True, choices=[('s1000', 'S-1000 - Informações do Empregador/Contribuinte/Órgão Público'), ('s1005', 'S-1005 - Tabela de Estabelecimentos, Obras ou Unidades de Órgãos Públicos'), ('s1010', 'S-1010 - Tabela de Rubricas'), ('s1020', 'S-1020 - Tabela de Lotações Tributárias'), ('s1030', 'S-1030 - Tabela de Cargos/Empregos Públicos'), ('s1035', 'S-1035 - Tabela de Carreiras Públicas'), ('s1040', 'S-1040 - Tabela de Funções/Cargos em Comissão'), ('s1050', 'S-1050 - Tabela de Horários/Turnos de Trabalho'), ('s1060', 'S-1060 - Tabela de Ambientes de Trabalho'), ('s1070', 'S-1070 - Tabela de Processos Administrativos/Judiciais'), ('s1080', 'S-1080 - Tabela de Operadores Portuários'), ('s1200', 'S-1200 - Remuneração de trabalhador vinculado ao Regime Geral de Previd. Social'), ('s1202', 'S-1202 - Remuneração de servidor vinculado a Regime Próprio de Previd. Social'), ('s1207', 'S-1207 - Benefícios previdenciários - RPPS'), ('s1210', 'S-1210 - Pagamentos de Rendimentos do Trabalho'), ('s1250', 'S-1250 - Aquisição de Produção Rural'), ('s1260', 'S-1260 - Comercialização da Produção Rural Pessoa Física'), ('s1270', 'S-1270 - Contratação de Trabalhadores Avulsos Não Portuários'), ('s1280', 'S-1280 - Informações Complementares aos Eventos Periódicos'), ('s1295', 'S-1295 - Solicitação de Totalização para Pagamento em Contingência'), ('s1298', 'S-1298 - Reabertura dos Eventos Periódicos'), ('s1299', 'S-1299 - Fechamento dos Eventos Periódicos'), ('s1300', 'S-1300 - Contribuição Sindical Patronal'), ('s2190', 'S-2190 - Admissão de Trabalhador - Registro Preliminar'), ('s2200', 'S-2200 - Cadastramento Inicial do Vínculo e Admissão/Ingresso de Trabalhador'), ('s2205', 'S-2205 - Alteração de Dados Cadastrais do Trabalhador'), ('s2206', 'S-2206 - Alteração de Contrato de Trabalho'), ('s2210', 'S-2210 - Comunicação de Acidente de Trabalho'), ('s2220', 'S-2220 - Monitoramento da Saúde do Trabalhador'), ('s2221', 'S-2221 - Exame Toxicológico do Motorista Profissional'), ('s2230', 'S-2230 - Afastamento Temporário'), ('s2240', 'S-2240 - Condições Ambientais do Trabalho - Fatores de Risco'), ('s2245', 'S-2245 - Treinamentos, Capacitações, Exercícios Simulados e Outras Anotações'), ('s2250', 'S-2250 - Aviso Prévio'), ('s2260', 'S-2260 - Convocação para Trabalho Intermitente'), ('s2298', 'S-2298 - Reintegração'), ('s2299', 'S-2299 - Desligamento'), ('s2300', 'S-2300 - Trabalhador Sem Vínculo de Emprego/Estatutário - Início'), ('s2306', 'S-2306 - Trabalhador Sem Vínculo de Emprego/Estatutário - Alteração Contratual'), ('s2399', 'S-2399 - Trabalhador Sem Vínculo de Emprego/Estatutário - Término'), ('s2400', 'S-2400 - Cadastro de Benefícios Previdenciários - RPPS'), ('s3000', 'S-3000 - Exclusão de eventos')], default='v02_05_00', max_length=20, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='evento_json',
            field=models.TextField(blank=True, default='{}', verbose_name='JSON'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='identidade',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='operacao',
            field=models.IntegerField(blank=True, choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')], null=True, verbose_name='Operações'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (1, 'Importado'), (2, 'Duplicado'), (3, 'Gerado'), (4, 'Erro na Geração'), (4, 'Assinado'), (6, 'Erro na Assinatura'), (7, 'Validado'), (8, 'Erro na validação'), (9, 'Aguardando envio de precedência'), (10, 'Aguardando envio'), (11, 'Enviado'), (12, 'Erro no Envio/Consulta'), (13, 'Processado')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='versao',
            field=models.CharField(blank=True, choices=[('v02_05_00', 'Versão 2.05.00')], default='v02_05_00', max_length=20, verbose_name='Versão'),
        ),
    ]
