# Generated by Django 2.2.13 on 2020-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0006_auto_20201031_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='procemi',
            field=models.IntegerField(choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Doméstico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Simplificado Pessoa Jurídica'), (5, '5 - Aplicativo governamental - Segurado Especial.')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='tpamb',
            field=models.IntegerField(choices=[(1, '1 - Produção'), (2, '2 - Produção restrita.')], null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='verproc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
