# Generated by Django 2.2.13 on 2020-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0009_auto_20201102_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissor',
            name='nrinsc',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
