# Generated by Django 2.2.13 on 2020-11-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0010_auto_20201102_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='transmissor_eventos_error',
            new_name='transmissor_evento_error',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='transmissor_eventos',
        ),
        migrations.AddField(
            model_name='eventos',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_transmissor_evento', to='esocial.TransmissorEventos'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (2, 'Enviado'), (2, 'Erro no envio'), (3, 'Consultado'), (4, 'Erro na consulta')], default=0),
        ),
    ]
