# Generated by Django 2.2.13 on 2020-11-10 16:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0011_auto_20201102_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/PycharmProjects/emensageria/certificados/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='procemi',
            field=models.IntegerField(choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Doméstico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Simplificado Pessoa Jurídica'), (5, '5 - Aplicativo governamental - Segurado Especial.')], default=1, null=True, verbose_name='Processo de emissão do evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tpamb',
            field=models.IntegerField(choices=[(1, '1 - Produção'), (2, '2 - Produção restrita.')], null=True, verbose_name='Identificação do ambiente'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='verproc',
            field=models.CharField(max_length=20, null=True, verbose_name='Versão do processo'),
        ),
    ]
