# Generated by Django 2.2.13 on 2020-12-16 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esocial', '0013_eventos_evento_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissorEventosArquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('servico', models.IntegerField(choices=[(1, 'WsEnviarLoteEventos'), (2, 'WsConsultarLoteEventos')], verbose_name='Serviço')),
                ('tipo', models.IntegerField(choices=[(1, 'Header'), (2, 'Request'), (2, 'Response')], verbose_name='Tipo')),
                ('arquivo', models.CharField(max_length=200, verbose_name='Nome do arquivo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do arquivo')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='esocial_transmissoreventosarquivos_created_by', to=settings.AUTH_USER_MODEL)),
                ('transmissor_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoreventosarquivos_transmissor_evento', to='esocial.TransmissorEventos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='esocial_transmissoreventosarquivos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo do transmissor do eSocial',
                'verbose_name_plural': 'Arquivos do transmissor do eSocial',
            },
        ),
    ]
