# Generated by Django 2.2.13 on 2020-12-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0014_transmissoreventosarquivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissoreventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (1, 'Aguardando envio'), (2, 'Enviando ...'), (3, 'Enviado'), (4, 'Erro no envio'), (5, 'Consultando ...'), (6, 'Consultado'), (7, 'Erro na consulta')], default=0),
        ),
        migrations.AlterField(
            model_name='transmissoreventosarquivos',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Header'), (2, 'Request'), (3, 'Response')], verbose_name='Tipo'),
        ),
    ]
