# Generated by Django 2.2.13 on 2020-12-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0015_auto_20201216_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacaoarquivoseventos',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='importacaoarquivoseventos',
            name='importacao_arquivos',
        ),
        migrations.RemoveField(
            model_name='importacaoarquivoseventos',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='arquivo',
            field=models.CharField(max_length=300, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='data_criacao',
            field=models.DateField(verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='permite_recuperacao',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], verbose_name='Permite recuperação'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='arquivo_header',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Arquivo header'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='arquivo_request',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Arquivo request'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='arquivo_response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Arquivo response'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='data_hora_consulta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da consulta'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='data_hora_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do envio'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='empregador_nrinsc',
            field=models.CharField(max_length=15, verbose_name='Número de inscrição do empregador'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='empregador_tpinsc',
            field=models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')], verbose_name='Tipo de inscrição do empregador'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='grupo',
            field=models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos Não Periódicos'), (3, '3 - Eventos Periódicos')], verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='ocorrencias_json',
            field=models.TextField(blank=True, null=True, verbose_name='Ocorrências'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='processamento_versao_aplicativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do aplicativo de processamento'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='recepcao_data_hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da recepção'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='recepcao_versao_aplicativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do aplicativo de recepção'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='resposta_codigo',
            field=models.CharField(blank=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advertências'), (301, '301 - Erro Servidor '), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inválido'), (403, '403 - Lote Incorreto - Versão do Schema não permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicitação de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicitação de Consulta Incorreta - Schema Inválido.'), (503, '503 - Solicitação de Consulta Incorreta - Versão do Schema Não Permitida.'), (504, '504 - Solicitação de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicitação de Consulta Incorreta - Consulta nula ou vazia.')], max_length=10, null=True, verbose_name='Código da Resposta'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='resposta_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da resposta'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='retorno_consulta_json',
            field=models.TextField(blank=True, null=True, verbose_name='Retorno da consulta'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='retorno_envio_json',
            field=models.TextField(blank=True, null=True, verbose_name='Retorno do envio'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (1, 'Aguardando envio'), (2, 'Enviando ...'), (3, 'Enviado'), (4, 'Erro no envio'), (5, 'Consultando ...'), (6, 'Consultado'), (7, 'Erro na consulta')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='tempo_estimado_conclusao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo estimado de conclusão'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='transmissor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoreventos_transmissor', to='esocial.Transmissor', verbose_name='Transmissor'),
        ),
        migrations.DeleteModel(
            name='ImportacaoArquivos',
        ),
        migrations.DeleteModel(
            name='ImportacaoArquivosEventos',
        ),
    ]
