# Generated by Django 2.2.13 on 2020-12-21 20:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0016_auto_20201221_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivos',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/PycharmProjects/emensageria/arquivos/eventos/esocial'), upload_to='', verbose_name='Arquivo'),
        ),
    ]
