# Generated by Django 2.2.13 on 2020-12-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0017_auto_20201221_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivos',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='permite_recuperacao',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=1, verbose_name='Permite recuperação'),
        ),
    ]
