# Generated by Django 2.2.13 on 2020-12-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0018_auto_20201221_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmissoreventosarquivos',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmissor_certificado', to='esocial.Certificados', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='endereco_completo',
            field=models.TextField(null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='logotipo',
            field=models.FileField(blank=True, null=True, upload_to='logotipo', verbose_name='Logotipo'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='nome_empresa',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='nrinsc',
            field=models.CharField(max_length=15, unique=True, verbose_name='Número de inscrição'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='tpinsc',
            field=models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')], verbose_name='Tipo de inscrição'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='transmissor_nrinsc',
            field=models.CharField(max_length=15, verbose_name='Número de inscrição do transmissor'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='transmissor_tpinsc',
            field=models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')], verbose_name='Tipo de inscrição do transmissor'),
        ),
        migrations.AlterField(
            model_name='transmissoreventosarquivos',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissoreventosarquivos_transmissor_evento', to='esocial.TransmissorEventos'),
        ),
    ]
