# Generated by Django 2.2.13 on 2020-12-22 10:39

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0019_auto_20201221_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='arquivo_original',
        ),
        migrations.AddField(
            model_name='arquivos',
            name='evento',
            field=models.ManyToManyField(blank=True, related_name='arquivos_evento', to='esocial.Eventos', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='arquivos',
            name='fonte',
            field=models.IntegerField(choices=[(0, 'Gerado pelo sistema'), (1, 'Importado')], default=1, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/PycharmProjects/emensageria/certificados/'), upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='nome',
            field=models.CharField(max_length=300, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='senha',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Senha'),
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='eventos',
            name='arquivo',
            field=models.ManyToManyField(blank=True, related_name='eventos_arquivo', to='esocial.Arquivos', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ocorrencias_json',
            field=models.TextField(blank=True, default='{}', verbose_name='Ocorrências'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='retorno_consulta_json',
            field=models.TextField(blank=True, default='{}', verbose_name='Retorno da consulta'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='retorno_envio_json',
            field=models.TextField(blank=True, default='{}', verbose_name='Retorno do envio'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_transmissor_evento', to='esocial.TransmissorEventos', verbose_name='Transmissor'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='transmissor_evento_error',
            field=models.ManyToManyField(blank=True, related_name='eventos_transmissor_eventos_erros', to='esocial.TransmissorEventos', verbose_name='Transmissores (Erro)'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='validacao_precedencia',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True, verbose_name='Validação de precedência'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='validacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Validações'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='campos',
            field=models.CharField(help_text='Inclua os campos separando eles por ponto e vírgula', max_length=500, verbose_name='Campos'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='sql',
            field=models.TextField(blank=True, null=True, verbose_name='Comando SQL'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='titulo',
            field=models.CharField(max_length=500, verbose_name='Título'),
        ),
    ]
