# Generated by Django 2.2.13 on 2020-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0020_auto_20201222_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissoreventos',
            name='resposta_codigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código da Resposta'),
        ),
    ]
