# Generated by Django 2.2.2 on 2021-05-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0021_auto_20201222_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivos',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
    ]
