# Generated by Django 2.2.2 on 2021-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0022_auto_20210518_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado (Aguardando validação)'), (1, 'Erro na validação (Aguardando correção)'), (4, 'Erro no Envio/Consulta (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (3, 'Enviado (Aguardando consulta)'), (5, 'Processado')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='versao',
            field=models.CharField(choices=[('v_S_01_00_00', 'Versão S-1.0')], default='v02_05_00', max_length=20, verbose_name='Versão'),
        ),
    ]
