# Generated by Django 2.2.2 on 2021-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0023_auto_20210528_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissor',
            name='endereco_completo',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
    ]
