# Generated by Django 4.2.18 on 2025-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Obrigatório. Informe o nome do usuário.', max_length=50, unique=True, verbose_name='Nome do usuário'),
        ),
    ]
