# Generated by Django 3.2 on 2021-06-05 11:06

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/PycharmProjects/emensageria/arquivos/eventos/reinf'), upload_to='', verbose_name='Arquivo')),
                ('permite_recuperacao', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=1, verbose_name='Permite recuperação')),
                ('fonte', models.IntegerField(choices=[(0, 'Gerado pelo sistema'), (1, 'Importado')], default=1, verbose_name='Fonte')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_created_by_reinf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('certificado', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/PycharmProjects/emensageria/certificados'), upload_to='', verbose_name='Arquivo')),
                ('senha', models.CharField(blank=True, max_length=300, null=True, verbose_name='Senha')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados_created_by_reinf', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='certificados_updated_by_reinf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificados',
                'verbose_name_plural': 'Certificados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identidade', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Identidade')),
                ('versao', models.CharField(choices=[('v_S_01_00_00', 'Versão S-1.0')], default='v_S_01_00_00', max_length=20, verbose_name='Versão')),
                ('evento', models.CharField(choices=[('s1000', 'S-1000 - Informações do Empregador/Contribuinte/Órgão Público'), ('s1005', 'S-1005 - Tabela de Estabelecimentos, Obras ou Unidades de Órgãos Públicos'), ('s1010', 'S-1010 - Tabela de Rubricas'), ('s1020', 'S-1020 - Tabela de Lotações Tributárias'), ('s1030', 'S-1030 - Tabela de Cargos/Empregos Públicos'), ('s1035', 'S-1035 - Tabela de Carreiras Públicas'), ('s1040', 'S-1040 - Tabela de Funções/Cargos em Comissão'), ('s1050', 'S-1050 - Tabela de Horários/Turnos de Trabalho'), ('s1060', 'S-1060 - Tabela de Ambientes de Trabalho'), ('s1070', 'S-1070 - Tabela de Processos Administrativos/Judiciais'), ('s1080', 'S-1080 - Tabela de Operadores Portuários'), ('s1200', 'S-1200 - Remuneração de trabalhador vinculado ao Regime Geral de Previd. Social'), ('s1202', 'S-1202 - Remuneração de servidor vinculado a Regime Próprio de Previd. Social'), ('s1207', 'S-1207 - Benefícios previdenciários - RPPS'), ('s1210', 'S-1210 - Pagamentos de Rendimentos do Trabalho'), ('s1250', 'S-1250 - Aquisição de Produção Rural'), ('s1260', 'S-1260 - Comercialização da Produção Rural Pessoa Física'), ('s1270', 'S-1270 - Contratação de Trabalhadores Avulsos Não Portuários'), ('s1280', 'S-1280 - Informações Complementares aos Eventos Periódicos'), ('s1295', 'S-1295 - Solicitação de Totalização para Pagamento em Contingência'), ('s1298', 'S-1298 - Reabertura dos Eventos Periódicos'), ('s1299', 'S-1299 - Fechamento dos Eventos Periódicos'), ('s1300', 'S-1300 - Contribuição Sindical Patronal'), ('s2190', 'S-2190 - Admissão de Trabalhador - Registro Preliminar'), ('s2200', 'S-2200 - Cadastramento Inicial do Vínculo e Admissão/Ingresso de Trabalhador'), ('s2205', 'S-2205 - Alteração de Dados Cadastrais do Trabalhador'), ('s2206', 'S-2206 - Alteração de Contrato de Trabalho'), ('s2210', 'S-2210 - Comunicação de Acidente de Trabalho'), ('s2220', 'S-2220 - Monitoramento da Saúde do Trabalhador'), ('s2221', 'S-2221 - Exame Toxicológico do Motorista Profissional'), ('s2230', 'S-2230 - Afastamento Temporário'), ('s2240', 'S-2240 - Condições Ambientais do Trabalho - Fatores de Risco'), ('s2245', 'S-2245 - Treinamentos, Capacitações, Exercícios Simulados e Outras Anotações'), ('s2250', 'S-2250 - Aviso Prévio'), ('s2260', 'S-2260 - Convocação para Trabalho Intermitente'), ('s2298', 'S-2298 - Reintegração'), ('s2299', 'S-2299 - Desligamento'), ('s2300', 'S-2300 - Trabalhador Sem Vínculo de Emprego/Estatutário - Início'), ('s2306', 'S-2306 - Trabalhador Sem Vínculo de Emprego/Estatutário - Alteração Contratual'), ('s2399', 'S-2399 - Trabalhador Sem Vínculo de Emprego/Estatutário - Término'), ('s2400', 'S-2400 - Cadastro de Benefícios Previdenciários - RPPS'), ('s3000', 'S-3000 - Exclusão de eventos')], max_length=20, verbose_name='Evento')),
                ('operacao', models.IntegerField(blank=True, choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')], null=True, verbose_name='Operações')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Cadastrado (Aguardando validação)'), (1, 'Erro na validação (Aguardando correção)'), (4, 'Erro no Envio/Consulta (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (3, 'Enviado (Aguardando consulta)'), (5, 'Consultado')], default=0, verbose_name='Status')),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)'), (5, '5 - CGC'), (6, '6 - CEI')], verbose_name='Tipo de inscrição')),
                ('nrinsc', models.CharField(max_length=15, verbose_name='Numero de inscrição')),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produção'), (2, '2 - Produção restrita.')], null=True, verbose_name='Identificação do ambiente')),
                ('procemi', models.IntegerField(choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Doméstico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Simplificado Pessoa Jurídica'), (5, '5 - Aplicativo governamental - Segurado Especial.')], default=1, null=True, verbose_name='Processo de emissão do evento')),
                ('verproc', models.CharField(max_length=20, null=True, verbose_name='Versão do processo')),
                ('validacao_precedencia', models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True, verbose_name='Validação de precedência')),
                ('validacoes', models.TextField(blank=True, null=True, verbose_name='Validações')),
                ('retorno_envio_json', models.TextField(blank=True, default='{}', verbose_name='Retorno do envio')),
                ('retorno_consulta_json', models.TextField(blank=True, default='{}', verbose_name='Retorno da consulta')),
                ('evento_json', models.TextField(blank=True, default='{}', verbose_name='JSON')),
                ('evento_xml', models.TextField(blank=True, null=True, verbose_name='XML')),
                ('ocorrencias_json', models.TextField(blank=True, default='{}', verbose_name='Ocorrências')),
                ('arquivo', models.ManyToManyField(blank=True, related_name='eventos_arquivo', to='reinf.Arquivos', verbose_name='Arquivo')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_created_by_reinf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['versao', 'evento', 'operacao', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Transmissor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transmissor_tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')], verbose_name='Tipo de inscrição do transmissor')),
                ('transmissor_nrinsc', models.CharField(max_length=15, verbose_name='Número de inscrição do transmissor')),
                ('nome_empresa', models.CharField(max_length=200, unique=True, verbose_name='Nome da empresa')),
                ('logotipo', models.FileField(blank=True, null=True, upload_to='logotipo', verbose_name='Logotipo')),
                ('endereco_completo', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')], verbose_name='Tipo de inscrição')),
                ('nrinsc', models.CharField(max_length=15, unique=True, verbose_name='Número de inscrição')),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmissor_certificado', to='reinf.certificados', verbose_name='Certificado')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissor_created_by_reinf', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='transmissor_updated_by_reinf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmissor',
                'verbose_name_plural': 'Transmissor',
            },
        ),
        migrations.CreateModel(
            name='TransmissorEventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empregador_tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')], verbose_name='Tipo de inscrição do empregador')),
                ('empregador_nrinsc', models.CharField(max_length=15, verbose_name='Número de inscrição do empregador')),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos Não Periódicos'), (3, '3 - Eventos Periódicos')], verbose_name='Grupo')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (1, 'Aguardando envio'), (2, 'Enviando ...'), (3, 'Enviado'), (4, 'Erro no envio'), (5, 'Consultando ...'), (6, 'Consultado'), (7, 'Erro na consulta')], default=0, verbose_name='Status')),
                ('resposta_codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código da Resposta')),
                ('resposta_descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da resposta')),
                ('data_hora_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do envio')),
                ('data_hora_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da consulta')),
                ('recepcao_data_hora', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da recepção')),
                ('recepcao_versao_aplicativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do aplicativo de recepção')),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Protocolo')),
                ('processamento_versao_aplicativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do aplicativo de processamento')),
                ('tempo_estimado_conclusao', models.IntegerField(blank=True, null=True, verbose_name='Tempo estimado de conclusão')),
                ('arquivo_header', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arquivo header')),
                ('arquivo_request', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arquivo request')),
                ('arquivo_response', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arquivo response')),
                ('retorno_envio_json', models.TextField(blank=True, null=True, verbose_name='Retorno do envio')),
                ('retorno_consulta_json', models.TextField(blank=True, null=True, verbose_name='Retorno da consulta')),
                ('ocorrencias_json', models.TextField(blank=True, null=True, verbose_name='Ocorrências')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissoreventos_created_by_reinf', to=settings.AUTH_USER_MODEL)),
                ('transmissor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoreventos_transmissor', to='reinf.transmissor', verbose_name='Transmissor')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='transmissoreventos_updated_by_reinf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmissor do eSocial',
                'verbose_name_plural': 'Transmissor do eSocial',
            },
        ),
        migrations.CreateModel(
            name='TransmissorEventosArquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servico', models.IntegerField(choices=[(1, 'WsEnviarLoteEventos'), (2, 'WsConsultarLoteEventos')], verbose_name='Serviço')),
                ('tipo', models.IntegerField(choices=[(1, 'Header'), (2, 'Request'), (3, 'Response')], verbose_name='Tipo')),
                ('arquivo', models.CharField(max_length=200, verbose_name='Nome do arquivo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do arquivo')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissoreventosarquivos_created_by_reinf', to=settings.AUTH_USER_MODEL)),
                ('transmissor_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissoreventosarquivos_transmissor_evento', to='reinf.transmissoreventos')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='transmissoreventosarquivos_updated_by_reinf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('campos', models.CharField(help_text='Inclua os campos separando eles por ponto e vírgula', max_length=500, verbose_name='Campos')),
                ('sql', models.TextField(blank=True, null=True, verbose_name='Comando SQL')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_created_by_reinf', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='relatorios_updated_by_reinf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatórios',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='EventosHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identidade', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Identidade')),
                ('versao', models.CharField(choices=[('v_S_01_00_00', 'Versão S-1.0')], default='v_S_01_00_00', max_length=20, verbose_name='Versão')),
                ('evento', models.CharField(choices=[('s1000', 'S-1000 - Informações do Empregador/Contribuinte/Órgão Público'), ('s1005', 'S-1005 - Tabela de Estabelecimentos, Obras ou Unidades de Órgãos Públicos'), ('s1010', 'S-1010 - Tabela de Rubricas'), ('s1020', 'S-1020 - Tabela de Lotações Tributárias'), ('s1030', 'S-1030 - Tabela de Cargos/Empregos Públicos'), ('s1035', 'S-1035 - Tabela de Carreiras Públicas'), ('s1040', 'S-1040 - Tabela de Funções/Cargos em Comissão'), ('s1050', 'S-1050 - Tabela de Horários/Turnos de Trabalho'), ('s1060', 'S-1060 - Tabela de Ambientes de Trabalho'), ('s1070', 'S-1070 - Tabela de Processos Administrativos/Judiciais'), ('s1080', 'S-1080 - Tabela de Operadores Portuários'), ('s1200', 'S-1200 - Remuneração de trabalhador vinculado ao Regime Geral de Previd. Social'), ('s1202', 'S-1202 - Remuneração de servidor vinculado a Regime Próprio de Previd. Social'), ('s1207', 'S-1207 - Benefícios previdenciários - RPPS'), ('s1210', 'S-1210 - Pagamentos de Rendimentos do Trabalho'), ('s1250', 'S-1250 - Aquisição de Produção Rural'), ('s1260', 'S-1260 - Comercialização da Produção Rural Pessoa Física'), ('s1270', 'S-1270 - Contratação de Trabalhadores Avulsos Não Portuários'), ('s1280', 'S-1280 - Informações Complementares aos Eventos Periódicos'), ('s1295', 'S-1295 - Solicitação de Totalização para Pagamento em Contingência'), ('s1298', 'S-1298 - Reabertura dos Eventos Periódicos'), ('s1299', 'S-1299 - Fechamento dos Eventos Periódicos'), ('s1300', 'S-1300 - Contribuição Sindical Patronal'), ('s2190', 'S-2190 - Admissão de Trabalhador - Registro Preliminar'), ('s2200', 'S-2200 - Cadastramento Inicial do Vínculo e Admissão/Ingresso de Trabalhador'), ('s2205', 'S-2205 - Alteração de Dados Cadastrais do Trabalhador'), ('s2206', 'S-2206 - Alteração de Contrato de Trabalho'), ('s2210', 'S-2210 - Comunicação de Acidente de Trabalho'), ('s2220', 'S-2220 - Monitoramento da Saúde do Trabalhador'), ('s2221', 'S-2221 - Exame Toxicológico do Motorista Profissional'), ('s2230', 'S-2230 - Afastamento Temporário'), ('s2240', 'S-2240 - Condições Ambientais do Trabalho - Fatores de Risco'), ('s2245', 'S-2245 - Treinamentos, Capacitações, Exercícios Simulados e Outras Anotações'), ('s2250', 'S-2250 - Aviso Prévio'), ('s2260', 'S-2260 - Convocação para Trabalho Intermitente'), ('s2298', 'S-2298 - Reintegração'), ('s2299', 'S-2299 - Desligamento'), ('s2300', 'S-2300 - Trabalhador Sem Vínculo de Emprego/Estatutário - Início'), ('s2306', 'S-2306 - Trabalhador Sem Vínculo de Emprego/Estatutário - Alteração Contratual'), ('s2399', 'S-2399 - Trabalhador Sem Vínculo de Emprego/Estatutário - Término'), ('s2400', 'S-2400 - Cadastro de Benefícios Previdenciários - RPPS'), ('s3000', 'S-3000 - Exclusão de eventos')], max_length=20, verbose_name='Evento')),
                ('operacao', models.IntegerField(blank=True, choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')], null=True, verbose_name='Operações')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Cadastrado (Aguardando validação)'), (1, 'Erro na validação (Aguardando correção)'), (4, 'Erro no Envio/Consulta (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (3, 'Enviado (Aguardando consulta)'), (5, 'Consultado')], default=0, verbose_name='Status')),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)'), (5, '5 - CGC'), (6, '6 - CEI')], verbose_name='Tipo de inscrição')),
                ('nrinsc', models.CharField(max_length=15, verbose_name='Numero de inscrição')),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produção'), (2, '2 - Produção restrita.')], null=True, verbose_name='Identificação do ambiente')),
                ('procemi', models.IntegerField(choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Doméstico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Simplificado Pessoa Jurídica'), (5, '5 - Aplicativo governamental - Segurado Especial.')], default=1, null=True, verbose_name='Processo de emissão do evento')),
                ('verproc', models.CharField(max_length=20, null=True, verbose_name='Versão do processo')),
                ('validacao_precedencia', models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True, verbose_name='Validação de precedência')),
                ('validacoes', models.TextField(blank=True, null=True, verbose_name='Validações')),
                ('retorno_envio_json', models.TextField(blank=True, default='{}', verbose_name='Retorno do envio')),
                ('retorno_consulta_json', models.TextField(blank=True, default='{}', verbose_name='Retorno da consulta')),
                ('evento_json', models.TextField(blank=True, default='{}', verbose_name='JSON')),
                ('evento_xml', models.TextField(blank=True, null=True, verbose_name='XML')),
                ('ocorrencias_json', models.TextField(blank=True, default='{}', verbose_name='Ocorrências')),
                ('arquivo', models.ManyToManyField(blank=True, related_name='eventoshistorico_arquivo_historico', to='reinf.Arquivos', verbose_name='Arquivo')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventoshistorico_created_by_reinf', to=settings.AUTH_USER_MODEL)),
                ('evt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evento_esocial', to='reinf.eventos', verbose_name='Evento')),
                ('transmissor_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissor_esocial_historico', to='reinf.transmissoreventos', verbose_name='Transmissor')),
                ('transmissor_evento_error', models.ManyToManyField(blank=True, related_name='eventoshistorico_transmissor_eventos_erros_historico', to='reinf.TransmissorEventos', verbose_name='Transmissores (Erro)')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='eventoshistorico_updated_by_reinf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do Evento',
                'verbose_name_plural': 'Histórico dos Eventos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='eventos',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissor_reinf', to='reinf.transmissoreventos', verbose_name='Transmissor'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='transmissor_evento_error',
            field=models.ManyToManyField(blank=True, related_name='eventos_transmissor_eventos_erros', to='reinf.TransmissorEventos', verbose_name='Transmissores (Erro)'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='eventos_updated_by_reinf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arquivos',
            name='evento',
            field=models.ManyToManyField(blank=True, related_name='arquivos_evento', to='reinf.Eventos', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='arquivos',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='arquivos_updated_by_reinf', to=settings.AUTH_USER_MODEL),
        ),
    ]
