# Generated by Django 3.2 on 2021-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinf', '0002_alter_eventoshistorico_identidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoshistorico',
            name='evento_json',
            field=models.TextField(blank=True, null=True, verbose_name='JSON'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='ocorrencias_json',
            field=models.TextField(blank=True, null=True, verbose_name='Ocorrências'),
        ),
    ]
