# Generated by Django 3.2.4 on 2021-06-16 22:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinf', '0004_auto_20210605_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/Projects/emensageria/certificados'), upload_to='', verbose_name='Arquivo'),
        ),
    ]
