# Generated by Django 3.2.4 on 2021-06-21 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reinf', '0005_alter_certificados_certificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmissoreventos',
            options={'verbose_name': 'Transmissor do Reinf', 'verbose_name_plural': 'Transmissor do Reinf'},
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='evt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evento_reinf', to='reinf.eventos', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissor_reinf_historico', to='reinf.transmissoreventos', verbose_name='Transmissor'),
        ),
    ]
