# Generated by Django 3.2.4 on 2021-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinf', '0006_auto_20210621_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado (Aguardando validação)'), (4, 'Erro na validação (Aguardando correção)'), (4, 'Erro no Envio/Consulta (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (3, 'Enviado (Aguardando consulta)'), (5, 'Consultado')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado (Aguardando validação)'), (4, 'Erro na validação (Aguardando correção)'), (4, 'Erro no Envio/Consulta (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (3, 'Enviado (Aguardando consulta)'), (5, 'Consultado')], default=0, verbose_name='Status'),
        ),
    ]
