# Generated by Django 3.2.4 on 2022-02-27 14:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinf', '0007_auto_20210627_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/PycharmProjects/emensageria/certificados'), upload_to='', verbose_name='Arquivo'),
        ),
    ]
