# Generated by Django 3.2 on 2021-06-05 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leiaute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('esocial_efdreinf', models.CharField(max_length=10)),
                ('versao', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=5000)),
                ('evento_codigo', models.CharField(max_length=50)),
                ('evento_slug', models.CharField(blank=True, max_length=500, null=True)),
                ('numero', models.IntegerField()),
                ('numero_esocial', models.IntegerField()),
                ('registro_campo', models.CharField(max_length=100)),
                ('registro_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('elemento', models.CharField(max_length=2)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('ocorrencias', models.CharField(max_length=10)),
                ('tamanho', models.IntegerField(blank=True, null=True)),
                ('casas_decimais', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('descricao_original', models.TextField(blank=True, null=True)),
                ('validacao', models.TextField(blank=True, null=True)),
                ('valores_validos', models.TextField(blank=True, null=True)),
                ('ordenacao', models.IntegerField(blank=True, null=True)),
                ('opcoes', models.TextField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo', models.TextField(blank=True, max_length=500, null=True)),
                ('input_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('input_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('input_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('input_choices_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('input_choices', models.TextField(blank=True, null=True)),
                ('input_html', models.TextField(blank=True, null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leiaute_created_by', to=settings.AUTH_USER_MODEL)),
                ('modelo_xml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leiaute_modelo_xml', to='contrib.leiaute')),
                ('modelo_xml_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leiaute_modelo_xml_fk', to='contrib.leiaute')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='leiaute_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leiaute',
                'verbose_name_plural': 'Leiaute',
            },
        ),
    ]
