# Generated by Django 3.2.4 on 2021-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_dicionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='leiaute',
            name='input_html_for',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leiaute',
            name='is_multiplas_ocorrencias',
            field=models.BooleanField(default=False),
        ),
    ]
