# Generated by Django 2.2.13 on 2020-08-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_settings', '0005_menu_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='priority_level',
            field=models.IntegerField(default=100, help_text='The bigger the priority', verbose_name='Priority Level'),
        ),
    ]
