# Generated by Django 2.2.13 on 2020-10-29 14:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=300)),
                ('certificado', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='G:\\Projetos\\emensageria/certificado/'), upload_to='')),
                ('senha', models.CharField(blank=True, max_length=300, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_certificados_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_certificados_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificados',
                'verbose_name_plural': 'Certificados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoArquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('arquivo', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Aguardando'), (1, 'Processando'), (2, 'Processado com sucesso'), (3, 'Erro - Processamento'), (4, 'Erro - Outros'), (5, 'Erro - Arquivo Inválido'), (6, 'Erro - Identidade já existente'), (7, 'Erro - Versão de leiaute incompatível'), (8, 'Erro - Validação de Leiaute')])),
                ('data_hora', models.DateTimeField(blank=True)),
                ('quant_total', models.IntegerField(blank=True, null=True)),
                ('quant_aguardando', models.IntegerField(blank=True, null=True)),
                ('quant_processado', models.IntegerField(blank=True, null=True)),
                ('quant_importado', models.IntegerField(blank=True, null=True)),
                ('quant_erros', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_importacaoarquivos_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_importacaoarquivos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação de Arquivos',
                'verbose_name_plural': 'Importação de Arquivos',
                'ordering': ['arquivo'],
            },
        ),
        migrations.CreateModel(
            name='Transmissor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('transmissor_tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('transmissor_nrinsc', models.CharField(max_length=15)),
                ('nome_empresa', models.CharField(max_length=200, unique=True)),
                ('data_abertura', models.DateField()),
                ('logotipo', models.FileField(blank=True, null=True, upload_to='logotipo')),
                ('endereco_completo', models.TextField()),
                ('nrinsc', models.CharField(max_length=15)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinf_transmissor_certificado', to='reinf.Certificados')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_transmissor_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_transmissor_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmissor',
                'verbose_name_plural': 'Transmissor',
            },
        ),
        migrations.CreateModel(
            name='TransmissorEventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('empregador_tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('empregador_nrinsc', models.CharField(max_length=15)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos Não Periódicos'), (3, '3 - Eventos Periódicos')])),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (1, 'Enviado'), (2, 'Erro no envio'), (3, 'Consultado'), (4, 'Erro na consulta')], default=0)),
                ('resposta_codigo', models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advertências'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inválido'), (403, '403 - Lote Incorreto - Versão do Schema não permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicitação de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicitação de Consulta Incorreta - Schema Inválido.'), (503, '503 - Solicitação de Consulta Incorreta - Versão do Schema Não Permitida.'), (504, '504 - Solicitação de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicitação de Consulta Incorreta - Consulta nula ou vazia.')], null=True)),
                ('resposta_descricao', models.TextField(blank=True, null=True)),
                ('recepcao_data_hora', models.DateTimeField(blank=True, null=True)),
                ('recepcao_versao_aplicativo', models.CharField(blank=True, max_length=50, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('processamento_versao_aplicativo', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo_estimado_conclusao', models.IntegerField(blank=True, null=True)),
                ('arquivo_header', models.CharField(blank=True, max_length=200, null=True)),
                ('arquivo_request', models.CharField(blank=True, max_length=200, null=True)),
                ('arquivo_response', models.CharField(blank=True, max_length=200, null=True)),
                ('data_hora_envio', models.DateTimeField(blank=True, null=True)),
                ('data_hora_consulta', models.DateTimeField(blank=True, null=True)),
                ('retorno_envio_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='retorno_envio_json')),
                ('retorno_consulta_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='retorno_consulta_json')),
                ('ocorrencias_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='ocorrencias_json')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_transmissoreventos_created_by', to=settings.AUTH_USER_MODEL)),
                ('transmissor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinf_transmissoreventos_transmissor', to='reinf.Transmissor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_transmissoreventos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmissor do eSocial',
                'verbose_name_plural': 'Transmissor do eSocial',
            },
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=500)),
                ('campos', models.CharField(max_length=500)),
                ('sql', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_relatorios_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_relatorios_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatórios',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='ImportacaoArquivosEventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('arquivo', models.CharField(blank=True, max_length=200, null=True)),
                ('evento', models.CharField(blank=True, max_length=100, null=True)),
                ('versao', models.CharField(blank=True, max_length=30, null=True)),
                ('identidade_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('identidade', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Aguardando'), (1, 'Processando'), (2, 'Processado com sucesso'), (3, 'Erro - Processamento'), (4, 'Erro - Outros'), (5, 'Erro - Arquivo Inválido'), (6, 'Erro - Identidade já existente'), (7, 'Erro - Versão de leiaute incompatível'), (8, 'Erro - Validação de Leiaute')], null=True)),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('validacoes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_importacaoarquivoseventos_created_by', to=settings.AUTH_USER_MODEL)),
                ('importacao_arquivos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='esocial_importacaoarquivoseventos_importacao_arquivos', to='reinf.ImportacaoArquivos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_importacaoarquivoseventos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eventos de Arquivos Importados',
                'verbose_name_plural': 'Eventos de Arquivos Importados',
                'ordering': ['importacao_arquivos', 'arquivo', 'evento', 'versao', 'identidade_evento', 'identidade'],
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('identidade', models.CharField(blank=True, max_length=36, null=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produção'), (2, '2 - Produção restrita.')], null=True)),
                ('procemi', models.IntegerField(choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Doméstico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Simplificado Pessoa Jurídica'), (5, '5 - Aplicativo governamental - Segurado Especial.')], default=1, null=True)),
                ('verproc', models.CharField(max_length=20, null=True)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)'), (5, '5 - CGC'), (6, '6 - CEI')], null=True)),
                ('nrinsc', models.CharField(max_length=15, null=True)),
                ('versao', models.CharField(blank=True, choices=[('v02_04_02', 'Versão 2.04.02'), ('v02_05_00', 'Versão 2.05.00')], default='v02_05_00', max_length=20)),
                ('validacao_precedencia', models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True)),
                ('validacoes', models.TextField(blank=True, null=True)),
                ('arquivo_original', models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], default=0, null=True)),
                ('arquivo', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (1, 'Importado'), (2, 'Duplicado'), (3, 'Gerado'), (4, 'Erro na Geração'), (4, 'Assinado'), (6, 'Erro na Assinatura'), (7, 'Validado'), (8, 'Erro na validação'), (9, 'Aguardando envio de precedência'), (10, 'Aguardando envio'), (11, 'Enviado'), (12, 'Erro no Envio/Consulta'), (13, 'Processado')], default=0)),
                ('operacao', models.IntegerField(blank=True, choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')], null=True)),
                ('retorno_envio_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='retorno_envio_json')),
                ('retorno_consulta_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='retorno_consulta_json')),
                ('evento_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='evento_json')),
                ('ocorrencias_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='ocorrencias_json')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_eventos_created_by', to=settings.AUTH_USER_MODEL)),
                ('transmissor_eventos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinf_eventos_transmissor_eventos', to='reinf.TransmissorEventos')),
                ('transmissor_eventos_error', models.ManyToManyField(blank=True, related_name='reinf_eventos_transmissor_eventos_erros', to='reinf.TransmissorEventos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_eventos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'],
            },
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('arquivo', models.CharField(max_length=300)),
                ('data_criacao', models.DateField()),
                ('permite_recuperacao', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')])),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_arquivos_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_arquivos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivos',
                'verbose_name_plural': 'Arquivos',
            },
        ),
    ]
