# Generated by Django 2.2.13 on 2020-11-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reinf', '0002_auto_20201030_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['versao', 'evento', 'operacao', 'status'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='transmissoreventos',
            options={'verbose_name': 'Transmissor do ', 'verbose_name_plural': 'Transmissor do '},
        ),
        migrations.AddField(
            model_name='eventos',
            name='evento',
            field=models.CharField(choices=[('s1000', 'S-1000 - Informações do Empregador/Contribuinte/Órgão Público'), ('s1005', 'S-1005 - Tabela de Estabelecimentos, Obras ou Unidades de Órgãos Públicos'), ('s1010', 'S-1010 - Tabela de Rubricas'), ('s1020', 'S-1020 - Tabela de Lotações Tributárias'), ('s1030', 'S-1030 - Tabela de Cargos/Empregos Públicos'), ('s1035', 'S-1035 - Tabela de Carreiras Públicas'), ('s1040', 'S-1040 - Tabela de Funções/Cargos em Comissão'), ('s1050', 'S-1050 - Tabela de Horários/Turnos de Trabalho'), ('s1060', 'S-1060 - Tabela de Ambientes de Trabalho'), ('s1070', 'S-1070 - Tabela de Processos Administrativos/Judiciais'), ('s1080', 'S-1080 - Tabela de Operadores Portuários'), ('s1200', 'S-1200 - Remuneração de trabalhador vinculado ao Regime Geral de Previd. Social'), ('s1202', 'S-1202 - Remuneração de servidor vinculado a Regime Próprio de Previd. Social'), ('s1207', 'S-1207 - Benefícios previdenciários - RPPS'), ('s1210', 'S-1210 - Pagamentos de Rendimentos do Trabalho'), ('s1250', 'S-1250 - Aquisição de Produção Rural'), ('s1260', 'S-1260 - Comercialização da Produção Rural Pessoa Física'), ('s1270', 'S-1270 - Contratação de Trabalhadores Avulsos Não Portuários'), ('s1280', 'S-1280 - Informações Complementares aos Eventos Periódicos'), ('s1295', 'S-1295 - Solicitação de Totalização para Pagamento em Contingência'), ('s1298', 'S-1298 - Reabertura dos Eventos Periódicos'), ('s1299', 'S-1299 - Fechamento dos Eventos Periódicos'), ('s1300', 'S-1300 - Contribuição Sindical Patronal'), ('s2190', 'S-2190 - Admissão de Trabalhador - Registro Preliminar'), ('s2200', 'S-2200 - Cadastramento Inicial do Vínculo e Admissão/Ingresso de Trabalhador'), ('s2205', 'S-2205 - Alteração de Dados Cadastrais do Trabalhador'), ('s2206', 'S-2206 - Alteração de Contrato de Trabalho'), ('s2210', 'S-2210 - Comunicação de Acidente de Trabalho'), ('s2220', 'S-2220 - Monitoramento da Saúde do Trabalhador'), ('s2221', 'S-2221 - Exame Toxicológico do Motorista Profissional'), ('s2230', 'S-2230 - Afastamento Temporário'), ('s2240', 'S-2240 - Condições Ambientais do Trabalho - Fatores de Risco'), ('s2245', 'S-2245 - Treinamentos, Capacitações, Exercícios Simulados e Outras Anotações'), ('s2250', 'S-2250 - Aviso Prévio'), ('s2260', 'S-2260 - Convocação para Trabalho Intermitente'), ('s2298', 'S-2298 - Reintegração'), ('s2299', 'S-2299 - Desligamento'), ('s2300', 'S-2300 - Trabalhador Sem Vínculo de Emprego/Estatutário - Início'), ('s2306', 'S-2306 - Trabalhador Sem Vínculo de Emprego/Estatutário - Alteração Contratual'), ('s2399', 'S-2399 - Trabalhador Sem Vínculo de Emprego/Estatutário - Término'), ('s2400', 'S-2400 - Cadastro de Benefícios Previdenciários - RPPS'), ('s3000', 'S-3000 - Exclusão de eventos')], default='v02_05_00', max_length=20, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='evento_json',
            field=models.TextField(blank=True, default='{}', verbose_name='JSON'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='identidade',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nrinsc',
            field=models.CharField(default=1, max_length=15, verbose_name='Numero de inscrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ocorrencias_json',
            field=models.TextField(blank=True, default='{}', verbose_name='ocorrencias_json'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='operacao',
            field=models.IntegerField(blank=True, choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')], null=True, verbose_name='Operações'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='retorno_consulta_json',
            field=models.TextField(blank=True, default='{}', verbose_name='retorno_consulta_json'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='retorno_envio_json',
            field=models.TextField(blank=True, default='{}', verbose_name='retorno_envio_json'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (1, 'Importado'), (2, 'Duplicado'), (3, 'Gerado'), (4, 'Erro na Geração'), (4, 'Assinado'), (6, 'Erro na Assinatura'), (7, 'Validado'), (8, 'Erro na validação'), (9, 'Aguardando envio de precedência'), (10, 'Aguardando envio'), (11, 'Enviado'), (12, 'Erro no Envio/Consulta'), (13, 'Processado')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tpinsc',
            field=models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)'), (5, '5 - CGC'), (6, '6 - CEI')], default=1, verbose_name='Tipo de inscrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='transmissor_eventos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_transmissor_eventos', to='reinf.TransmissorEventos'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='transmissor_eventos_error',
            field=models.ManyToManyField(blank=True, related_name='eventos_transmissor_eventos_erros', to='reinf.TransmissorEventos'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='versao',
            field=models.CharField(choices=[('v02_00_00', 'Versão 2.00.00')], default='v02_05_00', max_length=20, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='importacaoarquivoseventos',
            name='importacao_arquivos',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='importacaoarquivoseventos_importacao_arquivos', to='reinf.ImportacaoArquivos'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='resposta_codigo',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advertências'), (301, '301 - Erro Servidor '), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inválido'), (403, '403 - Lote Incorreto - Versão do Schema não permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicitação de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicitação de Consulta Incorreta - Schema Inválido.'), (503, '503 - Solicitação de Consulta Incorreta - Versão do Schema Não Permitida.'), (504, '504 - Solicitação de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicitação de Consulta Incorreta - Consulta nula ou vazia.')], null=True),
        ),
    ]
