# Generated by Django 2.2.13 on 2020-12-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinf', '0003_auto_20201102_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='evento_xml',
            field=models.TextField(blank=True, null=True, verbose_name='XML'),
        ),
    ]
