# Generated by Django 2.2.13 on 2020-12-16 22:13

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reinf', '0004_eventos_evento_xml'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmissoreventos',
            options={'verbose_name': 'Transmissor do eSocial', 'verbose_name_plural': 'Transmissor do eSocial'},
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='transmissor_eventos',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='transmissor_eventos_error',
        ),
        migrations.RemoveField(
            model_name='transmissor',
            name='data_abertura',
        ),
        migrations.AddField(
            model_name='eventos',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_transmissor_evento', to='reinf.TransmissorEventos'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='transmissor_evento_error',
            field=models.ManyToManyField(blank=True, related_name='eventos_transmissor_eventos_erros', to='reinf.TransmissorEventos'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/PycharmProjects/emensageria/certificados/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='evento',
            field=models.CharField(choices=[('s1000', 'S-1000 - Informações do Empregador/Contribuinte/Órgão Público'), ('s1005', 'S-1005 - Tabela de Estabelecimentos, Obras ou Unidades de Órgãos Públicos'), ('s1010', 'S-1010 - Tabela de Rubricas'), ('s1020', 'S-1020 - Tabela de Lotações Tributárias'), ('s1030', 'S-1030 - Tabela de Cargos/Empregos Públicos'), ('s1035', 'S-1035 - Tabela de Carreiras Públicas'), ('s1040', 'S-1040 - Tabela de Funções/Cargos em Comissão'), ('s1050', 'S-1050 - Tabela de Horários/Turnos de Trabalho'), ('s1060', 'S-1060 - Tabela de Ambientes de Trabalho'), ('s1070', 'S-1070 - Tabela de Processos Administrativos/Judiciais'), ('s1080', 'S-1080 - Tabela de Operadores Portuários'), ('s1200', 'S-1200 - Remuneração de trabalhador vinculado ao Regime Geral de Previd. Social'), ('s1202', 'S-1202 - Remuneração de servidor vinculado a Regime Próprio de Previd. Social'), ('s1207', 'S-1207 - Benefícios previdenciários - RPPS'), ('s1210', 'S-1210 - Pagamentos de Rendimentos do Trabalho'), ('s1250', 'S-1250 - Aquisição de Produção Rural'), ('s1260', 'S-1260 - Comercialização da Produção Rural Pessoa Física'), ('s1270', 'S-1270 - Contratação de Trabalhadores Avulsos Não Portuários'), ('s1280', 'S-1280 - Informações Complementares aos Eventos Periódicos'), ('s1295', 'S-1295 - Solicitação de Totalização para Pagamento em Contingência'), ('s1298', 'S-1298 - Reabertura dos Eventos Periódicos'), ('s1299', 'S-1299 - Fechamento dos Eventos Periódicos'), ('s1300', 'S-1300 - Contribuição Sindical Patronal'), ('s2190', 'S-2190 - Admissão de Trabalhador - Registro Preliminar'), ('s2200', 'S-2200 - Cadastramento Inicial do Vínculo e Admissão/Ingresso de Trabalhador'), ('s2205', 'S-2205 - Alteração de Dados Cadastrais do Trabalhador'), ('s2206', 'S-2206 - Alteração de Contrato de Trabalho'), ('s2210', 'S-2210 - Comunicação de Acidente de Trabalho'), ('s2220', 'S-2220 - Monitoramento da Saúde do Trabalhador'), ('s2221', 'S-2221 - Exame Toxicológico do Motorista Profissional'), ('s2230', 'S-2230 - Afastamento Temporário'), ('s2240', 'S-2240 - Condições Ambientais do Trabalho - Fatores de Risco'), ('s2245', 'S-2245 - Treinamentos, Capacitações, Exercícios Simulados e Outras Anotações'), ('s2250', 'S-2250 - Aviso Prévio'), ('s2260', 'S-2260 - Convocação para Trabalho Intermitente'), ('s2298', 'S-2298 - Reintegração'), ('s2299', 'S-2299 - Desligamento'), ('s2300', 'S-2300 - Trabalhador Sem Vínculo de Emprego/Estatutário - Início'), ('s2306', 'S-2306 - Trabalhador Sem Vínculo de Emprego/Estatutário - Alteração Contratual'), ('s2399', 'S-2399 - Trabalhador Sem Vínculo de Emprego/Estatutário - Término'), ('s2400', 'S-2400 - Cadastro de Benefícios Previdenciários - RPPS'), ('s3000', 'S-3000 - Exclusão de eventos')], default='v1_04_00', max_length=20, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='procemi',
            field=models.IntegerField(choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Doméstico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Simplificado Pessoa Jurídica'), (5, '5 - Aplicativo governamental - Segurado Especial.')], default=1, null=True, verbose_name='Processo de emissão do evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tpamb',
            field=models.IntegerField(choices=[(1, '1 - Produção'), (2, '2 - Produção restrita.')], null=True, verbose_name='Identificação do ambiente'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='verproc',
            field=models.CharField(max_length=20, null=True, verbose_name='Versão do processo'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='versao',
            field=models.CharField(choices=[('v2_05_00', 'Versão 2.05.00')], default='v1_04_00', max_length=20, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='certificado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transmissor_certificado', to='reinf.Certificados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='endereco_completo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='nrinsc',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='ocorrencias_json',
            field=models.TextField(blank=True, null=True, verbose_name='ocorrencias_json'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='retorno_consulta_json',
            field=models.TextField(blank=True, null=True, verbose_name='retorno_consulta_json'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='retorno_envio_json',
            field=models.TextField(blank=True, null=True, verbose_name='retorno_envio_json'),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (1, 'Aguardando envio'), (2, 'Enviando ...'), (3, 'Enviado'), (4, 'Erro no envio'), (5, 'Consultando ...'), (6, 'Consultado'), (7, 'Erro na consulta')], default=0),
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='transmissor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoreventos_transmissor', to='reinf.Transmissor'),
        ),
        migrations.CreateModel(
            name='TransmissorEventosArquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('servico', models.IntegerField(choices=[(1, 'WsEnviarLoteEventos'), (2, 'WsConsultarLoteEventos')], verbose_name='Serviço')),
                ('tipo', models.IntegerField(choices=[(1, 'Header'), (2, 'Request'), (3, 'Response')], verbose_name='Tipo')),
                ('arquivo', models.CharField(max_length=200, verbose_name='Nome do arquivo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do arquivo')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_transmissoreventosarquivos_created_by', to=settings.AUTH_USER_MODEL)),
                ('transmissor_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoreventosarquivos_transmissor_evento', to='reinf.TransmissorEventos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reinf_transmissoreventosarquivos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo do transmissor do eSocial',
                'verbose_name_plural': 'Arquivos do transmissor do eSocial',
            },
        ),
    ]
