# Generated by Django 3.2 on 2021-06-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoshistorico',
            name='identidade',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Identidade'),
        ),
    ]
