# Generated by Django 4.2.17 on 2025-01-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='transmissor_evento_error',
        ),
        migrations.RemoveField(
            model_name='eventoshistorico',
            name='transmissor_evento_error',
        ),
    ]
