# Generated by Django 4.2.18 on 2025-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotes',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterField(
            model_name='eventos',
            name='verproc',
            field=models.CharField(default='2.0.4', max_length=20, null=True, verbose_name='Versão do processo'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='versao',
            field=models.CharField(choices=[('v_S_01_00_00', 'Versão S-1.0'), ('v_S_01_01_00', 'Versão S-1.1'), ('v_S_01_02_00', 'Versão S-1.2'), ('v_S_01_03_00', 'Versão S-1.3')], default='v_S_01_03_00', max_length=20, verbose_name='Versão'),
        ),
    ]
