# Generated by Django 4.2.18 on 2025-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0003_alter_lotes_options_alter_eventos_verproc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='verproc',
            field=models.CharField(default='2.1.0', max_length=20, null=True, verbose_name='Versão do processo'),
        ),
    ]
