# Generated by Django 4.2.18 on 2025-03-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0004_alter_eventos_verproc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificados',
            options={'ordering': ['-id'], 'verbose_name': 'Certificados', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['-id'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventoshistorico',
            options={'ordering': ['-id'], 'verbose_name': 'Histórico do Evento', 'verbose_name_plural': 'Histórico dos Eventos'},
        ),
        migrations.AlterModelOptions(
            name='lotes',
            options={'ordering': ['-id'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='transmissor',
            options={'ordering': ['-id'], 'verbose_name': 'Transmissor', 'verbose_name_plural': 'Transmissor'},
        ),
        migrations.AlterField(
            model_name='eventos',
            name='verproc',
            field=models.CharField(default='2.1.1', max_length=20, null=True, verbose_name='Versão do processo'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado'), (8, 'Assinado'), (1, 'Aguardando envio'), (2, 'Enviando ...'), (3, 'Enviado'), (4, 'Erro no envio'), (5, 'Consultando ...'), (6, 'Consultado'), (7, 'Erro na consulta')], default=0, verbose_name='Status'),
        ),
    ]
