# Generated by Django 3.2.4 on 2021-06-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0004_auto_20210605_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='procemi',
            field=models.IntegerField(choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Doméstico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Simplificado Pessoa Jurídica'), (5, '5 - Aplicativo governamental - Segurado Especial.')], default=1, verbose_name='Processo de emissão do evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tpamb',
            field=models.IntegerField(choices=[(1, '1 - Produção'), (2, '2 - Produção restrita.')], default=2, verbose_name='Identificação do ambiente'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='evt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_esocial', to='esocial.eventos', verbose_name='Evento'),
        ),
    ]
