# Generated by Django 3.2.4 on 2021-06-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0005_auto_20210613_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmissoreventos',
            options={'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissor_esocial_historico', to='esocial.transmissoreventos', verbose_name='Transmissor'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='nrinsc',
            field=models.CharField(max_length=15, unique=True, verbose_name='Número de inscrição do empregador'),
        ),
        migrations.AlterField(
            model_name='transmissor',
            name='tpinsc',
            field=models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econômica de Pessoa Física)'), (4, '4 - CNO (Cadastro Nacional de Obra)')], verbose_name='Tipo de inscrição do empregador'),
        ),
    ]
