# Generated by Django 3.2.4 on 2021-06-14 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0006_auto_20210614_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado (Aguardando validação)'), (1, 'Erro (Aguardando correção)'), (4, 'Erro (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (3, 'Enviado (Aguardando consulta)'), (5, 'Consultado')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='transmissor_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmissor_esocial', to='esocial.transmissoreventos', verbose_name='Lote/Transmissor'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='transmissor_evento_error',
            field=models.ManyToManyField(blank=True, related_name='eventos_transmissor_eventos_erros', to='esocial.TransmissorEventos', verbose_name='Lote/Transmissor (Erro)'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrado (Aguardando validação)'), (1, 'Erro (Aguardando correção)'), (4, 'Erro (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (3, 'Enviado (Aguardando consulta)'), (5, 'Consultado')], default=0, verbose_name='Status'),
        ),
    ]
