# Generated by Django 3.2.4 on 2021-06-16 22:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0007_auto_20210614_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='is_aberto',
            field=models.BooleanField(default=True, verbose_name='Está aberto para edição'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='origem',
            field=models.IntegerField(choices=[(0, 'Sistema'), (1, 'Api')], default=0, verbose_name='Origem do evento'),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/Projects/emensageria/arquivos'), upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/marcelovasconcellos/Projects/emensageria/certificados'), upload_to='', verbose_name='Arquivo'),
        ),
    ]
