# Generated by Django 3.2.4 on 2021-06-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0008_auto_20210616_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoshistorico',
            name='is_aberto',
            field=models.BooleanField(default=True, verbose_name='Está aberto para edição'),
        ),
        migrations.AddField(
            model_name='eventoshistorico',
            name='origem',
            field=models.IntegerField(choices=[(0, 'Sistema'), (1, 'Api')], default=0, verbose_name='Origem do evento'),
        ),
    ]
