# Generated by Django 3.2.4 on 2021-06-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0016_auto_20210622_2148'),
    ]

    operations = [
        migrations.RunSQL("""  
            UPDATE public.esocial_eventos
                SET status=1
                WHERE status=4;
            UPDATE public.esocial_eventoshistorico
                SET status=1
                WHERE status=4;
        """)
    ]
