# Generated by Django 3.2.4 on 2021-07-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0018_auto_20210627_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Importado pela API'), (0, 'Cadastrado (Aguardando validação)'), (1, 'Erro (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (6, 'Enviando ...'), (3, 'Enviado (Aguardando consulta)'), (7, 'Consultando ...'), (5, 'Consultado')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventoshistorico',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Importado pela API'), (0, 'Cadastrado (Aguardando validação)'), (1, 'Erro (Aguardando correção)'), (2, 'Validado (Aguardando envio)'), (6, 'Enviando ...'), (3, 'Enviado (Aguardando consulta)'), (7, 'Consultando ...'), (5, 'Consultado')], default=0, verbose_name='Status'),
        ),
    ]
