# Generated by Django 3.2.4 on 2021-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0020_auto_20210716_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissoreventos',
            name='retorno_consulta_lote_json',
            field=models.TextField(blank=True, null=True, verbose_name='Retorno da consulta (Lote)'),
        ),
        migrations.AddField(
            model_name='transmissoreventos',
            name='retorno_envio_lote_json',
            field=models.TextField(blank=True, null=True, verbose_name='Retorno do envio (Lote)'),
        ),
    ]
