# Generated by Django 3.2.4 on 2021-07-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0021_auto_20210731_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='verproc',
            field=models.CharField(default='1.1.0', max_length=20, null=True, verbose_name='Versão do processo'),
        ),
    ]
