# Generated by Django 3.2.4 on 2021-08-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0022_alter_eventos_verproc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmissoreventos',
            name='retorno_consulta_lote_json',
        ),
        migrations.RemoveField(
            model_name='transmissoreventos',
            name='retorno_envio_lote_json',
        ),
        migrations.AddField(
            model_name='eventos',
            name='retorno_consulta_lote_json',
            field=models.TextField(blank=True, default='{}', verbose_name='Retorno do lote da consulta'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='retorno_envio_lote_json',
            field=models.TextField(blank=True, default='{}', verbose_name='Retorno do lote do envio'),
        ),
        migrations.AddField(
            model_name='eventoshistorico',
            name='retorno_consulta_lote_json',
            field=models.TextField(blank=True, default='{}', verbose_name='Retorno do lote da consulta'),
        ),
        migrations.AddField(
            model_name='eventoshistorico',
            name='retorno_envio_lote_json',
            field=models.TextField(blank=True, default='{}', verbose_name='Retorno do lote do envio'),
        ),
    ]
