# Generated by Django 3.2.25 on 2024-11-01 19:06

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0028_auto_20241011_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='arquivos',
            field=models.ManyToManyField(blank=True, related_name='eventos_arquivo', to='esocial.Arquivos', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='eventoshistorico',
            name='arquivos',
            field=models.ManyToManyField(blank=True, related_name='eventoshistorico_arquivo_historico', to='esocial.Arquivos', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/arquivos'), upload_to='', verbose_name='Arquivo'),
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='eventos',
            name='arquivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Arquivo'),
        ),
        migrations.RemoveField(
            model_name='eventoshistorico',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='eventoshistorico',
            name='arquivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='sql',
            field=models.TextField(default='', verbose_name='Comando SQL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transmissoreventos',
            name='transmissor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transmissoreventos_transmissor', to='esocial.transmissor', verbose_name='Transmissor'),
            preserve_default=False,
        ),
    ]
